const messages = {
  errorEmailAlreadyUsed: "This email address has already been used.",
  errorIncorrectEmailOrPassword: "The email or password is incorrect.",
  errorInvalidAbout: "Your profile’s about section cannot exceed 140 characters.",
  errorInvalidAuthor: "Please enter your book’s author.",
  errorInvalidEmail: "Please enter a valid email address.",
  errorInvalidNumberOfPages: "The number of pages must be at least 1.",
  errorInvalidPassword: "The password must be at least 8 characters long.",
  errorInvalidTitle: "Please enter your book’s title.",
  errorInvalidUsername: "Your username must be between 2 and 40 characters long.",
  errorNoChallengeFound: "No challenge found.",
  errorNoSessionFound: "No session found",
  errorNoProfileFound: "No profile found.",
  errorNotAuthorized: "You are not authorized to perform this action.",
  errorNoUserFound: "No user found.",
  errorUnmatchedPasswords: "Passwords must match.",
  errorUsernameAlreadyUsed: "This username has already been used.",
  successCreatedChallenge: "Your reading challenge has been created.",
  successCreatedProfile: "Your profile has been created.",
  successCreatedSession: "Your reading session has been created.",
  successDeletedChallenge: "Your reading challenge has been deleted.",
  successDeletedProfileAndUser: "Your profile and account have been deleted.",
  successEmailSent: "An email with a link to reset your password has been sent.",
  successSignedIn: "You are signed in.",
  successProfileFound: "The profile you were looking for was found.",
  successRegisteredUser: "You have been registered.",
  successUpdatedChallenge: "Your challenge has been updated.",
  successUpdatedProfile: "Your profile has been updated."
};

module.exports = messages;