export const GET_ERRORS = "GET_ERRORS";

export const FETCH_CURRENT_PROFILE = "FETCH_CURRENT_PROFILE";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const SET_CURRENT_PROFILE = "SET_CURRENT_PROFILE";
export const CLEAR_CURRENT_PROFILE = "CLEAR_CURRENT_PROFILE";

export const FETCH_CHALLENGES = "FETCH_CHALLENGES";
export const SET_CHALLENGES = "SET_CHALLENGES";
export const FETCH_CURRENT_CHALLENGE = "FETCH_CURRENT_CHALLENGE";
export const SET_CURRENT_CHALLENGE = "SET_CURRENT_CHALLENGE";