export const GET_ERRORS = "GET_ERRORS";

export const SET_CURRENT_USER = "SET_CURRENT_USER";

export const FETCH_CURRENT_PROFILE_REQUEST = "FETCH_CURRENT_PROFILE_REQUEST";
export const FETCH_CURRENT_PROFILE_SUCCESS = "FETCH_CURRENT_PROFILE_SUCCESS";
export const CLEAR_CURRENT_PROFILE = "CLEAR_CURRENT_PROFILE";

export const FETCH_CHALLENGES_REQUEST = "FETCH_CHALLENGES_REQUEST";
export const FETCH_CHALLENGES_SUCCESS = "FETCH_CHALLENGES_SUCCESS";