export const GET_ERRORS = "GET_ERRORS";

export const FETCH_CURRENT_PROFILE = "FETCH_CURRENT_PROFILE";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const SET_CURRENT_PROFILE = "SET_CURRENT_PROFILE";
export const CLEAR_CURRENT_PROFILE = "CLEAR_CURRENT_PROFILE";

export const FETCH_CURRENT_CHALLENGE = "FETCH_CURRENT_CHALLENGE";